### ISSUE TITLE
Facebook Autoreply is not working

### ISSUE THREAD

**Issue by jigneshhadiya2** [it5prasoon/Auto-Reply-Android#23]

**Comment by it5prasoon** [comment]
Can you elaborate whole issue here? Because it is working fine in our End.

**Comment by jigneshhadiya2** [comment]
Auto reply on Facebook Message is not working at my end on Facebook app and Messenger both.

**Comment by it5prasoon** [comment]
Please checkout the updated version v1.22.0. I have made some feature and UI enhancements and fixed some known major bugs.
